const localisation = {
  en: {
    password: "Password",
    login: "Login",
    forgotPassword: "Forgot password?",
    recepientAddress: "Recepient adress",
    amount: "Amount",
    send: "Send",
    bytecode: "Bytecode",
    deployContrant: "DeployContract",
    swap: "Swap tokens",
    oneDay: "1 day",
    oneWeek: "1 week",
    oneMonth: "1 month",
    oneYear: "1 year",
    createProof: "Create proof",
    calldata: "Calldata...",
    callContract: "Call contract",
    copyPK: "Copy private key",
    warningPK:
      "Don`t give private key to anyone! Anyone with private key get access to all account funds!",
    logOut: "Log out",
    putMnemonic: "Put your mnemonic phrase: ",
    newPassword: "New password",
    confirmPasswordLabel: "Confirm new password",
    confirmPassword: "Confirm password",
    confirm: "Confirm",
    proceed: "Procced",
    next: "Next",
    previous: "Previous",
    putLabel: "Put missing words to phrase",
    watchLabel: "Make sure nobody is watching",
    revealMnemonic: "Reveal mnemonnic phrase",
    toRecover: "Import from phrase",
    toRegister: "To register",
    toLogin: "To login",
    providePasswordError: "Provide password!",
    provideConfirmPasswordError: "Provide password confirmation!",
    txMined: "Transaction mined: ",
    addressCopied: "Address copied to clipboard!",
    putAddressError: "Put address!",
    putValueError: "Put value!",
    unexpectedError: "Something went wrong. Try again later.",
    txSendError: "An error occurred while sending the transaction!",
    pkCopyPopup: "Private key copied to clipboard!",
    invalidMnemonic: "Invalid mnemonic",
    passwordMismatch: "Password don`t match!",
    wrongPassword: "Wrong password!",
    wrongPhrase: "Wrong phrase!",
    textCopied: "Text copied to clipboard!",
    txFailError: "Transaction failed!",
    revertError: "Contract deployed, but revert occured!",
    phraseCopied: "Copy to clipboard",
  },
  ua: {
    password: "Пароль",
    login: "Увійти",
    forgotPassword: "Забули пароль?",
    recepientAddress: "Адреса отримувача",
    amount: "Сума",
    send: "Відправити",
    bytecode: "Байт-код",
    deployContrant: "Розгорнути контракт",
    swap: "Обмін токенів",
    oneDay: "1 день",
    oneWeek: "1 тиждень",
    oneMonth: "1 місяць",
    oneYear: "1 рік",
    createProof: "Створити доказ",
    calldata: "Викликові дані...",
    callContract: "Викликати контракт",
    copyPK: "Скопіювати приватний ключ",
    warningPK:
      "Не передавайте приватний ключ нікому! Будь-хто з приватним ключем отримає доступ до всіх коштів на рахунку!",
    logOut: "Вийти",
    putMnemonic: "Введіть свою мнемонічну фразу: ",
    newPassword: "Новий пароль",
    confirmPasswordLabel: "Підтвердіть новий пароль",
    confirmPassword: "Підтвердити пароль",
    proceed: "Продовжити",
    next: "Далі",
    providePasswordError: "Введіть пароль!",
    provideConfirmPasswordError: "Введіть підтвердження пароля!",
    txMined: "Транзакцію підтверджено: ",
    addressCopied: "Адресу скопійовано в буфер обміну!",
    putAddressError: "Введіть адресу!",
    putValueError: "Введіть значення!",
    unexpectedError: "Щось пішло не так. Спробуйте пізніше.",
    txSendError: "Сталася помилка під час відправки транзакції!",
    pkCopyPopup: "Приватний ключ скопійовано в буфер обміну!",
    invalidMnemonic: "Неправильна мнемонічна фраза",
    passwordMismatch: "Паролі не співпадають!",
    wrongPassword: "Неправильний пароль!",
    wrongPhrase: "Неправильна фраза!",
    textCopied: "Текст скопійовано в буфер обміну!",
    txFailError: "Транзакція не виконана!",
    revertError: "Контракт розгорнуто, але сталася відміна!",
    confirm: "Підтвердити",
    previous: "Назад",
    putLabel: "Вставте відсутні слова у фразу",
    watchLabel: "Переконайтеся, що ніхто не підглядає",
    revealMnemonic: "Показати мнемонічну фразу",
    toRecover: "Імпортувати з фрази",
    toLogin: "До входу",
    phraseCopied: "Cкопіювати фразу",
    toRegister: "Зареєструватись",
  },
  es: {
    password: "Contraseña",
    login: "Iniciar sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    recepientAddress: "Dirección del destinatario",
    amount: "Cantidad",
    send: "Enviar",
    bytecode: "Bytecode",
    deployContrant: "Desplegar contrato",
    swap: "Intercambiar tokens",
    oneDay: "1 día",
    oneWeek: "1 semana",
    oneMonth: "1 mes",
    oneYear: "1 año",
    createProof: "Crear prueba",
    calldata: "Datos de llamada...",
    callContract: "Llamar contrato",
    copyPK: "Copiar clave privada",
    warningPK: "¡No des la clave privada a nadie! ¡Cualquiera con la clave privada tendrá acceso a todos los fondos de la cuenta!",
    logOut: "Cerrar sesión",
    putMnemonic: "Introduce tu frase mnemotécnica: ",
    newPassword: "Nueva contraseña",
    confirmPasswordLabel: "Confirmar nueva contraseña",
    confirmPassword: "Confirmar contraseña",
    confirm: "Confirmar",
    proceed: "Proceder",
    next: "Siguiente",
    previous: "Anterior",
    putLabel: "Introduce las palabras que faltan en la frase",
    watchLabel: "Asegúrate de que nadie esté mirando",
    revealMnemonic: "Revelar frase mnemotécnica",
    toRecover: "Importar desde frase",
    toRegister: "Registrarse",
    toLogin: "Iniciar sesión",
    providePasswordError: "¡Proporcione la contraseña!",
    provideConfirmPasswordError: "¡Proporcione la confirmación de la contraseña!",
    txMined: "Transacción minada: ",
    addressCopied: "Dirección copiada al portapapeles!",
    putAddressError: "¡Introduce la dirección!",
    putValueError: "¡Introduce el valor!",
    unexpectedError: "Algo salió mal. Inténtalo de nuevo más tarde.",
    txSendError: "¡Ocurrió un error al enviar la transacción!",
    pkCopyPopup: "Clave privada copiada al portapapeles!",
    invalidMnemonic: "Mnemónico inválido",
    passwordMismatch: "¡Las contraseñas no coinciden!",
    wrongPassword: "¡Contraseña incorrecta!",
    wrongPhrase: "¡Frase incorrecta!",
    textCopied: "Texto copiado al portapapeles!",
    txFailError: "¡Transacción fallida!",
    revertError: "Contrato desplegado, pero ocurrió una reversión!",
    phraseCopied: "Copiar al portapapeles",
  },
  de: {
    password: "Passwort",
    login: "Anmelden",
    forgotPassword: "Passwort vergessen?",
    recepientAddress: "Empfängeradresse",
    amount: "Betrag",
    send: "Senden",
    bytecode: "Bytecode",
    deployContrant: "Vertrag bereitstellen",
    swap: "Tokens tauschen",
    oneDay: "1 Tag",
    oneWeek: "1 Woche",
    oneMonth: "1 Monat",
    oneYear: "1 Jahr",
    createProof: "Beweis erstellen",
    calldata: "Calldata...",
    callContract: "Vertrag aufrufen",
    copyPK: "Privaten Schlüssel kopieren",
    warningPK: "Geben Sie den privaten Schlüssel niemandem weiter! Jeder, der einen privaten Schlüssel hat, kann auf das gesamte Guthaben auf Ihrem Konto zugreifen",
    logOut: "Abmelden",
    putMnemonic: "Geben Sie Ihre mnemonische Phrase ein: ",
    newPassword: "Neues Passwort",
    confirmPasswordLabel: "Neues Passwort bestätigen",
    confirmPassword: "Passwort bestätigen",
    confirm: "Bestätigen",
    proceed: "Fortfahren",
    next: "Weiter",
    previous: "Zurück",
    putLabel: "Fehlende Wörter in die Phrase einfügen",
    watchLabel: "Stellen Sie sicher, dass niemand zuschaut",
    revealMnemonic: "Mnemonische Phrase anzeigen",
    toRecover: "Aus Phrase importieren",
    toRegister: "Registrieren",
    toLogin: "Anmelden",
    providePasswordError: "Passwort angeben!",
    provideConfirmPasswordError: "Passwortbestätigung angeben!",
    txMined: "Transaktion bestätigt: ",
    addressCopied: "Adresse in Zwischenablage kopiert!",
    putAddressError: "Adresse eingeben!",
    putValueError: "Wert eingeben!",
    unexpectedError: "Etwas ist schiefgelaufen. Bitte versuchen Sie es später erneut.",
    txSendError: "Beim Senden der Transaktion ist ein Fehler aufgetreten!",
    pkCopyPopup: "Privater Schlüssel in Zwischenablage kopiert!",
    invalidMnemonic: "Ungültige mnemonische Phrase",
    passwordMismatch: "Passwörter stimmen nicht überein!",
    wrongPassword: "Falsches Passwort!",
    wrongPhrase: "Falsche Phrase!",
    textCopied: "Text in Zwischenablage kopiert!",
    txFailError: "Transaktion fehlgeschlagen!",
    revertError: "Vertrag bereitgestellt, aber Rücksetzung aufgetreten!",
    phraseCopied: "In Zwischenablage kopieren",
  }
};

async function getValueByKey(key, lang) {
  return localisation[lang][key];
}

async function getValueByKeyNoLang(key) {
  let lang = await getLang();
  return localisation[lang][key];
}

async function nextLang(lang) {
  switch (lang) {
    case "en":
      await saveLang("ua");
      break;
    case "ua":
      await saveLang("es");
      break;
    case "es":
      await saveLang("de");
      break;
    case "de":
      await saveLang("en");
      break;
    default:
      await saveLang("en");
      break;
  }
}

